import { useEffect, useRef, useState } from 'react'
import { toast } from 'sonner'
import { useMutation } from '@tanstack/react-query'
import {
  Check,
  ChevronDown,
  ChevronRight,
  Loader2,
  LogOut,
  Pencil,
  Play,
  Plus,
  Rocket,
  Square,
  Trash2,
  TriangleAlert,
  X,
} from 'lucide-react'
import { deployProject, LANDING_URL } from '@/lib/api'
import { useProjectStatus, useSetProjectStatus } from '@/hooks/config'
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu'
import { Dialog, DialogContent, DialogTitle } from '@/components/ui/dialog'
import {
  useCreateProject,
  useCurrentProject,
  useDeleteProject,
  useProjects,
  useRenameProject,
  type Project,
} from '@/hooks/projects'
import { ThemeToggle } from '@/components/shell/ThemeToggle'
import { useAuthStore } from '@/stores/auth'
import { useWorkspaceStore, type PaneMode } from '@/stores/workspace'

const dialogInputClass =
  'w-full rounded-md border border-border bg-background px-2.5 py-2 font-mono text-xs text-heading placeholder-faint focus:border-primary focus:outline-none'

export function NewProjectDialog() {
  const open = useWorkspaceStore((s) => s.newProjectOpen)
  const setOpen = useWorkspaceStore((s) => s.setNewProjectOpen)
  const setProject = useWorkspaceStore((s) => s.setProject)
  const createProject = useCreateProject()

  const [name, setName] = useState('')

  const submit = () => {
    const trimmed = name.trim()
    if (!trimmed || createProject.isPending) return
    // No resources: a new project starts empty and they are added from the
    // sidebar (or generated by the AI pane).
    createProject.mutate(
      { name: trimmed },
      {
        onSuccess: (created) => {
          setProject(created.tenantId)
          setOpen(false)
          setName('')
          toast.success(`Provisioned ${created.tenantId}`)
        },
        onError: (e) => toast.error(`Could not create project: ${e.message}`),
      },
    )
  }

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogContent className="w-80 border-border bg-card p-4" showCloseButton={false}>
        <DialogTitle className="text-sm font-semibold text-foreground">New project</DialogTitle>
        <input
          type="text"
          autoFocus
          placeholder="project-name"
          value={name}
          onChange={(e) => setName(e.target.value)}
          onKeyDown={(e) => {
            if (e.key === 'Enter') submit()
          }}
          className={dialogInputClass}
        />
        <div className="mt-2 flex items-center justify-end gap-2">
          <button
            className="rounded-md px-3 py-1.5 font-mono text-xs text-muted-foreground hover:text-heading"
            onClick={() => setOpen(false)}
          >
            Cancel
          </button>
          <button
            className="rounded-md bg-primary px-3 py-1.5 font-mono text-xs font-semibold text-primary-foreground hover:bg-primary-hover disabled:opacity-60"
            disabled={createProject.isPending}
            onClick={submit}
          >
            {createProject.isPending ? 'Creating…' : 'Create'}
          </button>
        </div>
      </DialogContent>
    </Dialog>
  )
}

/**
 * Deleting deprovisions the tenant on the core and drops the row — there is no
 * undo, so unlike rename this one earns a dialog. It spells out what goes, and
 * Cancel takes focus so a stray Enter cannot confirm it.
 */
function DeleteProjectDialog({
  tenantId,
  name,
  resourceCount,
  open,
  onOpenChange,
}: {
  tenantId: string
  name: string
  resourceCount: number
  open: boolean
  onOpenChange: (open: boolean) => void
}) {
  const deleteProject = useDeleteProject()
  const status = useProjectStatus(tenantId)
  const setStatus = useSetProjectStatus(tenantId)
  const running = status === 'active'

  const stop = useMutation({
    mutationFn: () => setStatus.mutateAsync('stopped'),
    onSuccess: () => toast.success(`${name} stopped — you can delete it now.`),
    onError: (e: Error) => toast.error(`Could not stop ${name}: ${e.message}`),
  })

  const submit = () => {
    if (deleteProject.isPending || running) return
    deleteProject.mutate(tenantId, {
      onSuccess: () => {
        onOpenChange(false)
        toast.success(`Deleted ${name}`)
      },
      onError: (e) => toast.error(`Could not delete ${name}: ${e.message}`),
    })
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="w-96 border-border bg-card p-4" showCloseButton={false}>
        <DialogTitle className="text-sm font-semibold text-foreground">Delete {name}?</DialogTitle>

        {running ? (
          // The API is serving. Say so plainly and offer the way forward rather
          // than a disabled button with no explanation.
          <div className="flex gap-2.5 rounded-md border border-warning-soft-border bg-warning-soft-weak p-3">
            <TriangleAlert className="mt-0.5 h-4 w-4 shrink-0 text-warning-ink" />
            <p className="font-mono text-[11px] leading-relaxed text-warning-emphasis">
              This project is running. Deleting it would take a live API down under whatever is
              calling it — stop it first.
            </p>
          </div>
        ) : (
          <p className="font-mono text-xs leading-relaxed text-muted-foreground">
            This deletes{' '}
            <span className="text-emphasis">
              {resourceCount} resource file{resourceCount === 1 ? '' : 's'}
            </span>{' '}
            and its settings, and takes <span className="text-emphasis">/{tenantId}</span> offline
            for good. It cannot be undone.
          </p>
        )}

        <div className="mt-2 flex items-center justify-end gap-2">
          <button
            autoFocus
            className="rounded-md px-3 py-1.5 font-mono text-xs text-muted-foreground hover:text-heading"
            onClick={() => onOpenChange(false)}
          >
            Cancel
          </button>
          {running ? (
            <button
              className="flex items-center gap-1.5 rounded-md border border-border px-3 py-1.5 font-mono text-xs text-body transition-colors hover:border-danger-fill/40 hover:text-danger-emphasis disabled:opacity-60"
              disabled={stop.isPending}
              onClick={() => stop.mutate()}
            >
              <Square className="h-3 w-3" />
              {stop.isPending ? 'Stopping…' : 'Stop API'}
            </button>
          ) : (
            <button
              className="flex items-center gap-1.5 rounded-md bg-danger-fill px-3 py-1.5 font-mono text-xs font-semibold text-primary-foreground transition-colors hover:bg-danger-fill-hover disabled:opacity-60"
              disabled={deleteProject.isPending}
              onClick={submit}
            >
              <Trash2 className="h-3 w-3" />
              {deleteProject.isPending ? 'Deleting…' : 'Delete project'}
            </button>
          )}
        </div>
      </DialogContent>
    </Dialog>
  )
}

/**
 * Renames in place, where the name already is — a one-field dialog is more
 * ceremony than the edit deserves. Enter or clicking away commits, Escape
 * reverts, and the field sizes itself to the text so the bar does not jump.
 */
function InlineRename({
  tenantId,
  initialName,
  onDone,
}: {
  tenantId: string
  initialName: string
  onDone: () => void
}) {
  const [name, setName] = useState(initialName)
  const rename = useRenameProject()
  // Enter commits and then unmounts this field, which can also fire blur.
  // Without this guard that submits the rename twice.
  const settled = useRef(false)

  const commit = () => {
    if (settled.current) return
    const trimmed = name.trim()
    if (!trimmed || trimmed === initialName) {
      settled.current = true
      return onDone()
    }
    settled.current = true
    rename.mutate(
      { tenantId, name: trimmed },
      {
        onSuccess: onDone,
        onError: (e) => {
          toast.error(`Rename failed: ${e.message}`)
          settled.current = false // let them fix it rather than losing the edit
        },
      },
    )
  }

  const cancel = () => {
    settled.current = true
    onDone()
  }

  // The field commits on blur, so a plain click on these buttons would blur
  // first and commit before the click ever landed — cancel could never cancel.
  // Suppressing mousedown keeps focus in the input so only onClick decides.
  const keepFocus = (e: React.MouseEvent) => e.preventDefault()

  return (
    <div className="flex items-center gap-1.5">
      <input
        type="text"
        autoFocus
        value={name}
        disabled={rename.isPending}
        onFocus={(e) => e.currentTarget.select()}
        onChange={(e) => setName(e.target.value)}
        onKeyDown={(e) => {
          if (e.key === 'Enter') commit()
          if (e.key === 'Escape') cancel()
        }}
        onBlur={commit}
        // Sized to the text: a fixed width would make everything beside it jump
        // the moment you start editing.
        style={{ width: `${Math.max(6, name.length + 1)}ch` }}
        className="rounded-none border-b border-primary/60 bg-transparent text-sm font-medium text-foreground focus:outline-none disabled:opacity-60"
      />
      <button
        title="Save"
        aria-label="Save name"
        disabled={rename.isPending}
        onMouseDown={keepFocus}
        onClick={commit}
        className="cursor-pointer text-primary-accent transition-colors hover:text-primary-ink disabled:opacity-60"
      >
        <Check className="h-3.5 w-3.5" />
      </button>
      <button
        title="Cancel"
        aria-label="Cancel rename"
        onMouseDown={keepFocus}
        onClick={cancel}
        className="cursor-pointer text-subtle transition-colors hover:text-emphasis"
      >
        <X className="h-3.5 w-3.5" />
      </button>
    </div>
  )
}

/** Switches the centre pane between the editor, AI chat, logs and diagnostics. */
function ModeToggle() {
  const current = useCurrentProject()
  const status = useProjectStatus(current?.tenantId)
  const stopped = status !== 'active'
  const paneMode = useWorkspaceStore((s) => s.paneMode)
  const setPaneMode = useWorkspaceStore((s) => s.setPaneMode)

  // A stopped API serves no traffic and answers 503 on every public route, so
  // these two panes have nothing to show. Stopping while one of them is open
  // would otherwise strand the user on a dead view — fall back to the editor.
  useEffect(() => {
    if (stopped && (paneMode === 'logs' || paneMode === 'diagnostics')) setPaneMode('editor')
  }, [stopped, paneMode, setPaneMode])

  const modes: { mode: PaneMode; label: string; needsLive?: boolean }[] = [
    { mode: 'editor', label: 'Editor' },
    { mode: 'ai', label: 'AI chat' },
    { mode: 'logs', label: 'Logs', needsLive: true },
    { mode: 'diagnostics', label: 'Diagnostics', needsLive: true },
    // Not needsLive: you manage keys and set up an agent regardless of whether
    // the API is currently serving traffic.
    { mode: 'keys', label: 'API keys' },
  ]

  return (
    <div className="flex items-center gap-1">
      {modes.map(({ mode, label, needsLive }) => {
        // No project reads as "not live" too — with nothing selected there is
        // no traffic to stream and nothing to diagnose.
        const disabled = Boolean(needsLive) && (stopped || !current)
        return (
          <button
            key={mode}
            onClick={() => setPaneMode(mode)}
            disabled={disabled}
            title={disabled ? `Available once the API is live (currently ${status})` : undefined}
            className={
              disabled
                ? 'cursor-not-allowed rounded-md border border-transparent px-2.5 py-1.5 font-mono text-xs text-faintest'
                : paneMode === mode
                  ? 'cursor-pointer rounded-md border border-primary-soft-border bg-primary-soft px-2.5 py-1.5 font-mono text-xs text-primary-ink'
                  : 'cursor-pointer rounded-md border border-transparent px-2.5 py-1.5 font-mono text-xs text-subtle hover:text-emphasis'
            }
          >
            {label}
          </button>
        )
      })}
    </div>
  )
}

/**
 * Holds a flag true for at least `ms` once it goes up.
 *
 * A deploy against a local core finishes in tens of milliseconds, so progress
 * feedback tied directly to isPending appears and disappears inside a frame or
 * two. That does not read as "it worked", it reads as a glitch.
 */
function useMinDuration(active: boolean, ms = 450): boolean {
  const [visible, setVisible] = useState(false)
  const startedAt = useRef(0)

  useEffect(() => {
    if (active) {
      startedAt.current = Date.now()
      setVisible(true)
      return
    }
    if (!visible) return
    const remaining = Math.max(0, ms - (Date.now() - startedAt.current))
    const timer = setTimeout(() => setVisible(false), remaining)
    return () => clearTimeout(timer)
  }, [active, visible, ms])

  return visible
}

/**
 * One control for publishing and for start/stop.
 *
 * Deploy is the primary action and stays clickable in every state: it promotes
 * staged drafts, and doing that while the API is already live is the common
 * case, so it cannot be swapped out for a Stop button. The start/stop toggle
 * therefore hangs off the same button as a menu rather than sitting beside it
 * — one control, both actions, and the destructive one is a deliberate second
 * click instead of a thing you hit by accident next to Deploy.
 */
function DeployControls({ tenantId }: { tenantId: string | undefined }) {
  const status = useProjectStatus(tenantId)
  const setStatus = useSetProjectStatus(tenantId)
  const stopped = status !== 'active'

  const deploy = useMutation({
    mutationFn: async () => {
      const res = await deployProject(tenantId!)
      // Deploying a stopped project brings it back up — one action, one click.
      if (stopped) await setStatus.mutateAsync('active')
      return res
    },
    onSuccess: (res) => {
      const files =
        res.promoted.length > 0
          ? `${res.promoted.length} file${res.promoted.length === 1 ? '' : 's'}: ${res.promoted.join(', ')}`
          : 'no draft changes'
      toast.success(stopped ? `API is live again (${files})` : `Deployed ${files}`)
    },
    onError: (e) => toast.error(`Deploy failed: ${e.message}`),
  })

  const toggleStatus = useMutation({
    mutationFn: () => setStatus.mutateAsync(stopped ? 'active' : 'stopped'),
    onSuccess: () =>
      toast.success(
        stopped ? 'API started — endpoints are serving again.' : 'API stopped — requests now answer 503.',
      ),
    onError: (e: Error) => toast.error(`Could not change status: ${e.message}`),
  })

  // Held briefly so fast round-trips still register as a state, not a flicker.
  const deploying = useMinDuration(deploy.isPending)
  const busy = deploying || deploy.isPending || toggleStatus.isPending

  return (
    <div className="flex items-stretch">
      <button
        onClick={() => deploy.mutate()}
        disabled={!tenantId || busy}
        className="flex cursor-pointer items-center gap-1.5 rounded-l-md bg-primary px-3 py-1.5 font-mono text-xs font-semibold text-primary-foreground transition-colors hover:bg-primary-hover disabled:opacity-60"
      >
        {/* Progress lives on the icon, not the label. Swapping the word to
            "Deploying…" and back inside ~50ms stutters; the word only changes
            when the API's state actually changes, which is worth reading. */}
        {deploying ? (
          <Loader2 className="h-3.5 w-3.5 shrink-0 animate-spin" />
        ) : (
          <Rocket className="h-3.5 w-3.5 shrink-0" />
        )}
        {/* Live already means published, so the action is a re-publish; while
            stopped the same button also brings the API back up, which reads as
            a plain Deploy.

            Fixed 8ch — the width of "Redeploy", exact because the font is
            monospace. Without it the button resizes with its label, and being
            in the right-aligned group it drags the mode toggle sideways. */}
        {/* With no project there is nothing deployed, so "Redeploy" would be a
            lie on the very first screen a new account sees. */}
        <span className="w-[8ch] text-center">{stopped || !tenantId ? 'Deploy' : 'Redeploy'}</span>
      </button>
      <DropdownMenu>
        <DropdownMenuTrigger asChild>
          <button
            title="More actions"
            disabled={!tenantId || busy}
            className="flex cursor-pointer items-center rounded-r-md border-l border-black/20 bg-primary px-1.5 text-primary-foreground transition-colors hover:bg-primary-hover disabled:opacity-60"
          >
            <ChevronDown className="h-3.5 w-3.5" />
          </button>
        </DropdownMenuTrigger>
        <DropdownMenuContent align="end" className="w-44 border-border bg-card p-1.5">
          <DropdownMenuItem
            onSelect={() => toggleStatus.mutate()}
            className={`flex cursor-pointer items-center gap-2 rounded-md px-2 py-1.5 font-mono text-xs ${
              stopped ? 'text-primary-ink' : 'text-danger-emphasis'
            }`}
          >
            {stopped ? <Play className="h-3 w-3" /> : <Square className="h-3 w-3" />}
            {toggleStatus.isPending
              ? stopped
                ? 'Starting…'
                : 'Stopping…'
              : stopped
                ? 'Start API'
                : 'Stop API'}
          </DropdownMenuItem>
        </DropdownMenuContent>
      </DropdownMenu>
    </div>
  )
}

/** Whether this project's API is serving — shown beside its name. */
function StatusBadge({ tenantId }: { tenantId: string }) {
  const status = useProjectStatus(tenantId)
  const stopped = status !== 'active'
  return (
    <span
      title={stopped ? 'Public endpoints answer 503' : 'Public endpoints are serving'}
      className="flex shrink-0 items-center gap-1.5 font-mono text-xs text-subtle"
    >
      <span className={`h-1.5 w-1.5 rounded-full ${stopped ? 'bg-border-stronger' : 'bg-primary'}`} />
      {stopped ? status : 'live'}
    </span>
  )
}

export function TopBar() {
  const { data: projects, isLoading } = useProjects()
  const current = useCurrentProject()
  const setProject = useWorkspaceStore((s) => s.setProject)
  const setNewProjectOpen = useWorkspaceStore((s) => s.setNewProjectOpen)
  const user = useAuthStore((s) => s.user)
  const logout = useAuthStore((s) => s.logout)
  // Signing out lands on the marketing site, not /login. Someone who clicked
  // "log out" chose to leave; the login form they'd otherwise be dropped on is
  // an invitation to come straight back, and reads as though the sign-out
  // failed. An *involuntary* logout — the 401 handler in the auth store — still
  // falls through to /login, where getting the session back is the whole point,
  // which is why this redirect lives at the click and not in the store.
  //
  // The hint cookie the landing nav reads is cleared synchronously inside
  // logout(), so the page we arrive at already renders its signed-out header.
  const signOut = () => {
    logout()
    window.location.href = LANDING_URL
  }
  const [renaming, setRenaming] = useState(false)
  const [menuOpen, setMenuOpen] = useState(false)
  // Which project the confirm dialog is about — any row in the list, not just
  // the one currently open.
  const [deleteTarget, setDeleteTarget] = useState<Project | null>(null)

  return (
    <div className="flex h-14 shrink-0 items-center gap-2.5 border-b border-border bg-background px-5">
      <img
        src="/stubbase-logo-text-light.svg"
        alt="Stubbase"
        className="h-5 w-auto dark:hidden"
      />
      <img
        src="/stubbase-logo-text-dark.svg"
        alt="Stubbase"
        className="hidden h-5 w-auto dark:block"
      />
      <ChevronRight className="h-3.5 w-3.5 text-faintest" />
      {/* `group` so the rename pencil can reveal on hover of the whole block. */}
      <div className="group flex items-center gap-2">
        {current && renaming ? (
          <InlineRename
            tenantId={current.tenantId}
            initialName={current.name}
            onDone={() => setRenaming(false)}
          />
        ) : (
        <DropdownMenu open={menuOpen} onOpenChange={setMenuOpen}>
          <DropdownMenuTrigger asChild>
            <button className="flex cursor-pointer items-center gap-1 text-sm font-medium text-foreground select-none">
              {current?.name ?? (isLoading ? 'Loading…' : 'No project')}
            </button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="start" className="w-56 border-border bg-card p-1.5">
            <DropdownMenuLabel className="px-2 py-1 text-[10px] font-semibold tracking-wide text-faint uppercase">
              Projects
            </DropdownMenuLabel>
            {(projects ?? []).map((p) => (
              <DropdownMenuItem
                key={p.tenantId}
                onSelect={() => setProject(p.tenantId)}
                className={`flex cursor-pointer items-center gap-2 rounded-md px-2 py-1.5 ${
                  p.tenantId === current?.tenantId ? 'bg-muted/80' : ''
                }`}
              >
                <div
                  className={`flex h-5 w-5 shrink-0 items-center justify-center rounded ${p.color} text-[10px] font-bold text-primary-foreground`}
                >
                  {p.name[0]?.toUpperCase()}
                </div>
                <span
                  className={`flex-1 truncate font-mono text-xs ${
                    p.tenantId === current?.tenantId ? 'text-heading' : 'text-body'
                  }`}
                >
                  {p.name}
                </span>
                {p.tenantId === current?.tenantId && (
                  <Check className="h-3 w-3 shrink-0 text-primary-accent" />
                )}
                <button
                  title={`Delete ${p.name}`}
                  aria-label={`Delete ${p.name}`}
                  /* The row selects on pointer-up, so a bare onClick here would
                     switch to the project as well as open the dialog. Swallow
                     the pointer events and drive it from onClick alone. */
                  onPointerDown={(e) => e.stopPropagation()}
                  onPointerUp={(e) => e.stopPropagation()}
                  onClick={(e) => {
                    e.stopPropagation()
                    e.preventDefault()
                    setMenuOpen(false) // get the menu out of the dialog's way
                    setDeleteTarget(p)
                  }}
                  /* Always visible, unlike the rename pencil: the menu is an
                     explicit surface you had to open, so the action should be
                     findable without hunting for it by hovering. */
                  className="shrink-0 cursor-pointer text-faintest transition-colors hover:text-danger-ink"
                >
                  <Trash2 className="h-3 w-3" />
                </button>
              </DropdownMenuItem>
            ))}
            <DropdownMenuSeparator className="my-1 bg-muted" />
            <DropdownMenuItem
              onSelect={() => setNewProjectOpen(true)}
              className="flex cursor-pointer items-center gap-2 rounded-md px-2 py-1.5 text-muted-foreground hover:text-heading"
            >
              <div className="flex h-5 w-5 shrink-0 items-center justify-center rounded border border-dashed border-border-stronger">
                <Plus className="h-3 w-3" />
              </div>
              <span className="font-mono text-xs">New project</span>
            </DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
        )}
        {current && !renaming && (
          <button
            title="Rename project"
            aria-label="Rename project"
            onClick={() => setRenaming(true)}
            /* Hidden until the name is hovered (or the button is keyboard
               focused). Opacity rather than display, so revealing it never
               shifts the status badge sitting next to it. */
            className="cursor-pointer text-faint opacity-0 transition-opacity group-hover:opacity-100 hover:text-emphasis focus-visible:opacity-100"
          >
            <Pencil className="h-3 w-3" />
          </button>
        )}
        {/* Hidden while renaming: the save/cancel pair is the only thing that
            should be competing for attention in that moment. */}
        {current && !renaming && <StatusBadge tenantId={current.tenantId} />}
      </div>

      <NewProjectDialog />
      {deleteTarget && (
        <DeleteProjectDialog
          key={deleteTarget.tenantId}
          tenantId={deleteTarget.tenantId}
          name={deleteTarget.name}
          resourceCount={deleteTarget.resources.length}
          open
          onOpenChange={(open) => !open && setDeleteTarget(null)}
        />
      )}

      <span className="flex-1" />
      <ModeToggle />
      <DeployControls tenantId={current?.tenantId} />
      <ThemeToggle />
      <button
        title={`Log out${user ? ` (${user.email})` : ''}`}
        onClick={signOut}
        className="flex h-7 w-7 cursor-pointer items-center justify-center rounded-md text-subtle transition-colors hover:bg-card hover:text-heading"
      >
        <LogOut className="h-3.5 w-3.5" />
      </button>
    </div>
  )
}
